name: Linting, Testing, Building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       node-version: [ 21.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm install
      - name: build production
        run: npm run build:prod
      - name: TS linter
        run: npm run lint:ts
      - name: CSS linter
        run: npm run lint:css
      - name: Unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: Ui regression testing
        run: npm run test:ui:ci
